{
  lib,
  pkgs,
  projectLookupNames,
  repoLookupNames,
}:

pkgs.runCommand "realm-completions" { } ''
  install -d \
    "$out/share/bash-completion/completions" \
    "$out/share/fish/vendor_completions.d" \
    "$out/share/zsh/site-functions"

  cat > "$out/share/fish/vendor_completions.d/realm.fish" <<'FISH'
  # Generated by realm package configuration.
  set -l realm_subcommands list user path show info enter shell run new edit rename request requests approve reject result logs runs display-env grants revoke grant help
  set -l project_names ${lib.concatStringsSep " " (map lib.escapeShellArg projectLookupNames)}
  set -l repo_names ${lib.concatStringsSep " " (map lib.escapeShellArg repoLookupNames)}

  complete -c realm -f
  complete -c realm -n '__fish_use_subcommand' -a "$realm_subcommands"
  complete -c realm -n '__fish_seen_subcommand_from list user path show info enter shell run' -l project -s p
  complete -c realm -n '__fish_seen_subcommand_from list user path show info enter shell run' -l repo -s r
  complete -c realm -n '__fish_seen_subcommand_from list' -l all -s a
  complete -c realm -n '__fish_seen_subcommand_from list' -l flat
  complete -c realm -n '__fish_seen_subcommand_from list user path show info enter shell run' -l here
  complete -c realm -n '__fish_seen_subcommand_from show info' -l json
  complete -c realm -n '__fish_seen_subcommand_from user path show info enter shell run request access edit rename' -a "$project_names"
  complete -c realm -n '__fish_seen_subcommand_from user path show info enter shell run; and __fish_seen_argument -l repo' -a "$repo_names"
  complete -c realm -n '__fish_seen_subcommand_from grant; and not __fish_seen_subcommand_from list requests show approve reject result logs runs revoke tui' -a 'list requests show approve reject result logs runs revoke tui'
  complete -c realm -n '__fish_seen_subcommand_from request; and not __fish_seen_subcommand_from access display sudo' -a 'access display sudo'
  complete -c realm -n '__fish_seen_subcommand_from request access' -l mode -r -a 'read act'
  complete -c realm -n '__fish_seen_subcommand_from request access request display' -l ttl -r
  complete -c realm -n '__fish_seen_subcommand_from request access request display request sudo' -l reason -r
  complete -c realm -n '__fish_seen_subcommand_from request display' -l display -r
  complete -c realm -n '__fish_seen_subcommand_from request sudo' -l timeout -r
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l write
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l catalog-dir -r
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l alias -r
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l user -r
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l unset-user
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l clear-aliases
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l scope
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l no-scope
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l include-descendants
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l no-include-descendants
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l include -r -a "$project_names"
  complete -c realm -n '__fish_seen_subcommand_from new edit rename' -l clear-include
  complete -c realm -n '__fish_seen_subcommand_from rename' -l keep-old-alias
  complete -c realm -n '__fish_seen_subcommand_from rename' -l recompute-user
  FISH

  cat > "$out/share/bash-completion/completions/realm" <<'BASH'
  # Generated by realm package configuration.
  _realm()
  {
    local cur prev words cword
    _init_completion || return
    local commands="list user path show info enter shell run new edit rename request requests approve reject result logs runs display-env grants revoke grant help"
    local projects="${lib.concatStringsSep " " projectLookupNames}"
    local repos="${lib.concatStringsSep " " repoLookupNames}"
    case "''${words[1]:-}" in
      user|path|show|info|enter|shell|run|edit|rename)
        if [[ " ''${words[*]} " == *" --repo "* || " ''${words[*]} " == *" -r "* ]]; then
          COMPREPLY=( $(compgen -W "$repos" -- "$cur") )
        else
          COMPREPLY=( $(compgen -W "$projects" -- "$cur") )
        fi
        ;;
      *)
        if [[ $cword -eq 1 ]]; then COMPREPLY=( $(compgen -W "$commands" -- "$cur") ); fi
        ;;
    esac
  }
  complete -F _realm realm
  BASH

  cat > "$out/share/zsh/site-functions/_realm" <<'ZSH'
  #compdef realm
  # Generated by realm package configuration.
  local -a commands projects repos
  commands=(list user path show info enter shell run new edit rename request requests approve reject result logs runs display-env grants revoke grant help)
  projects=(${lib.concatStringsSep " " (map lib.escapeShellArg projectLookupNames)})
  repos=(${lib.concatStringsSep " " (map lib.escapeShellArg repoLookupNames)})
  if (( CURRENT == 2 )); then
    _describe -t commands 'realm subcommand' commands
  elif [[ ''${words[2]} == (user|path|show|info|enter|shell|run|edit|rename) ]]; then
    _describe -t projects 'project' projects
    _describe -t repos 'repo' repos
  fi
  ZSH
''
