{
  lib,
  pkgs,
  projectLookupNames,
  repoLookupNames,
}:

pkgs.runCommand "project-completions" { } ''
  install -d \
    "$out/share/bash-completion/completions" \
    "$out/share/fish/vendor_completions.d" \
    "$out/share/zsh/site-functions"

  cat > "$out/share/fish/vendor_completions.d/project.fish" <<'FISH'
  # Generated by project package configuration.
  set -l project_subcommands list user path enter shell here run repo new edit rename request requests show approve reject result grants revoke approvals approval help
  set -l project_names ${lib.concatStringsSep " " (map lib.escapeShellArg projectLookupNames)}
  set -l repo_names ${lib.concatStringsSep " " (map lib.escapeShellArg repoLookupNames)}
  set -l project_write_options --write --catalog-dir --alias --user --unset-user --clear-aliases --scope --no-scope --include-descendants --no-include-descendants --include --clear-include

  complete -c project -f
  complete -c project -n '__fish_use_subcommand' -a "$project_subcommands"
  complete -c project -n '__fish_seen_subcommand_from user path enter shell run edit rename' -a "$project_names"
  complete -c project -n '__fish_seen_subcommand_from repo; and not __fish_seen_subcommand_from list path user show info enter' -a 'list path user show info enter'
  complete -c project -n '__fish_seen_subcommand_from repo list' -a "$project_names"
  complete -c project -n '__fish_seen_subcommand_from repo path repo user repo show repo info repo enter' -a "$repo_names"
  complete -c project -n '__fish_seen_subcommand_from request; and not __fish_seen_subcommand_from access sudo' -a 'access sudo'
  complete -c project -n '__fish_seen_subcommand_from approval; and not __fish_seen_subcommand_from list requests show approve reject result revoke tui approvals' -a 'list requests show approve reject result revoke tui approvals'
  complete -c project -n '__fish_seen_subcommand_from request access' -a "$project_names"
  complete -c project -n '__fish_seen_subcommand_from request access' -l mode -r -a 'read act'
  complete -c project -n '__fish_seen_subcommand_from request access' -l ttl -r
  complete -c project -n '__fish_seen_subcommand_from request access request sudo' -l reason -r
  complete -c project -n '__fish_seen_subcommand_from request sudo' -l timeout -r
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l write
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l catalog-dir -r
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l alias -r
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l user -r
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l unset-user
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l clear-aliases
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l scope
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l no-scope
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l include-descendants
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l no-include-descendants
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l include -r -a "$project_names"
  complete -c project -n '__fish_seen_subcommand_from new edit rename' -l clear-include
  complete -c project -n '__fish_seen_subcommand_from rename' -l keep-old-alias
  complete -c project -n '__fish_seen_subcommand_from rename' -l recompute-user
  complete -c project -n 'not __fish_seen_subcommand_from list user path enter shell here run repo new edit rename request requests show approve reject result grants revoke approvals approval help; and __fish_use_subcommand' -a "$project_names"
  FISH

  cat > "$out/share/bash-completion/completions/project" <<'BASH'
  # Generated by project package configuration.
  _project()
  {
    local cur prev words cword
    _init_completion || return

    local commands="list user path enter shell here run repo new edit rename request requests show approve reject result grants revoke approvals approval help"
    local projects="${lib.concatStringsSep " " projectLookupNames}"
    local repos="${lib.concatStringsSep " " repoLookupNames}"

    case "''${words[1]:-}" in
      user|path|enter|shell|run|edit|rename)
        if [[ $cword -eq 2 ]]; then
          COMPREPLY=( $(compgen -W "$projects" -- "$cur") )
        fi
        ;;
      repo)
        if [[ $cword -eq 2 ]]; then
          COMPREPLY=( $(compgen -W "list path user show info enter" -- "$cur") )
        elif [[ $cword -eq 3 && ''${words[2]} == list ]]; then
          COMPREPLY=( $(compgen -W "$projects" -- "$cur") )
        elif [[ $cword -eq 3 ]]; then
          COMPREPLY=( $(compgen -W "$repos" -- "$cur") )
        fi
        ;;
      approval)
        if [[ $cword -eq 2 ]]; then
          COMPREPLY=( $(compgen -W "list requests show approve reject result revoke tui approvals" -- "$cur") )
        fi
        ;;
      *)
        if [[ $cword -eq 1 ]]; then
          COMPREPLY=( $(compgen -W "$commands $projects" -- "$cur") )
        fi
        ;;
    esac
  }
  complete -F _project project
  BASH

  cat > "$out/share/zsh/site-functions/_project" <<'ZSH'
  #compdef project
  # Generated by project package configuration.
  local -a commands projects
  commands=(list user path enter shell here run repo new edit rename request requests show approve reject result grants revoke approvals approval help)
  projects=(${lib.concatStringsSep " " (map lib.escapeShellArg projectLookupNames)})
  repos=(${lib.concatStringsSep " " (map lib.escapeShellArg repoLookupNames)})

  if (( CURRENT == 2 )); then
    _describe -t commands 'project subcommand' commands
    _describe -t projects 'project' projects
  elif [[ ''${words[2]} == (user|path|enter|shell|run|edit|rename) && CURRENT == 3 ]]; then
    _describe -t projects 'project' projects
  elif [[ ''${words[2]} == repo && CURRENT == 3 ]]; then
    local -a repo_commands
    repo_commands=(list path user show info enter)
    _describe -t repo-commands 'project repo subcommand' repo_commands
  elif [[ ''${words[2]} == approval && CURRENT == 3 ]]; then
    local -a approval_commands
    approval_commands=(list requests show approve reject result revoke tui approvals)
    _describe -t approval-commands 'project approval subcommand' approval_commands
  elif [[ ''${words[2]} == repo && ''${words[3]} == list && CURRENT == 4 ]]; then
    _describe -t projects 'project' projects
  elif [[ ''${words[2]} == repo && ''${words[3]} == (path|user|show|info|enter) && CURRENT == 4 ]]; then
    _describe -t repos 'repo' repos
  fi
  ZSH
''
